# introduccion a estructura de datos

# introduccion a las series

In [2]:
import numpy as np
import pandas as pd

In [4]:
ventas=pd.Series([22,15,70])
ventas

0    22
1    15
2    70
dtype: int64

In [6]:
ventas=pd.Series([22,15,70], index=["enero", "febrero", "marzo"])
ventas

enero      22
febrero    15
marzo      70
dtype: int64

In [7]:
ventas[0]

<ipython-input-7-eacc5df2ea8a>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ventas[0]

22

In [8]:
ventas["enero"]

22

In [9]:
#para conocer el tipo de datos dentro de las series
ventas.dtype

dtype('int64')

In [10]:
#Para conocer el nombre de los indices
ventas.index

Index(['enero', 'febrero', 'marzo'], dtype='object')

In [11]:
ventas.values

array([22, 15, 70])

In [12]:
#Cambiar el nombre a la feature o caracteristica
ventas.name="ventas mensuales"
ventas

enero      22
febrero    15
marzo      70
Name: ventas mensuales, dtype: int64

In [14]:
#Poner un titulo a los index
ventas.index.name="Meses"
ventas

Meses
enero      22
febrero    15
marzo      70
Name: ventas mensuales, dtype: int64

In [15]:
ventas.shape

(3,)

##Creando seies desde diccionarios

In [30]:
d={"enero":7, "febrero":9, "marzo":3}
type(d)

dict

In [35]:
s=pd.Series(d)
s

enero      7
febrero    9
marzo      3
dtype: int64

In [36]:
s.name= "valores"
s

enero      7
febrero    9
marzo      3
Name: valores, dtype: int64

In [38]:
juan=pd.Series(d,index=["enero","febrero","marzo","abril"])
juan

enero      7.0
febrero    9.0
marzo      3.0
abril      NaN
dtype: float64

#DATAGRAMAS

In [19]:
medidas=pd.DataFrame(
   { "Humedad":[41,20,30,80],
    "Salinidad":[22,15,30,30],
    "Maquinaria":["si","no","no","si"],
    "Acidez":["alta","media","baja","baja"],
    "ph":[3,5,9,12]},
    index=["la Ureña","La predregoza","Maria Bonita","Peru"]
)

medidas

               Humedad  Salinidad Maquinaria Acidez  ph
la Ureña            41         22         si   alta   3
La predregoza       20         15         no  media   5
Maria Bonita        30         30         no   baja   9
Peru                80         30         si   alta  12

In [20]:
medidas.index.name="fincas"
medidas

               Humedad  Salinidad Maquinaria Acidez  ph
fincas
la Ureña            41         22         si   alta   3
La predregoza       20         15         no  media   5
Maria Bonita        30         30         no   baja   9
Peru                80         30         si   alta  12

In [21]:
print(medidas.dtypes)

Humedad        int64
Salinidad      int64
Maquinaria    object
Acidez        object
ph             int64
dtype: object

In [22]:
medidas.index

Index(['la Ureña', 'La predregoza', 'Maria Bonita', 'Peru'], dtype='object', name='fincas')

In [23]:
medidas.columns

Index(['Humedad', 'Salinidad', 'Maquinaria', 'Acidez', 'ph'], dtype='object')

In [24]:
medidas.dtypes

Humedad        int64
Salinidad      int64
Maquinaria    object
Acidez        object
ph             int64
dtype: object

In [26]:
#EL eje 0 corresponde a las filas y el eje 1 al indice de  las columnas
medidas.loc["Maria Bonita","Humedad"]

30

In [27]:
medidas.axes

[Index(['la Ureña', 'La predregoza', 'Maria Bonita', 'Peru'], dtype='object', name='fincas'),
 Index(['Humedad', 'Salinidad', 'Maquinaria', 'Acidez', 'ph'], dtype='object')]

In [28]:
#Conociendo los valores del dataframe
medidas.values

array([[41, 22, 'si', 'alta', 3],
       [20, 15, 'no', 'media', 5],
       [30, 30, 'no', 'baja', 9],
       [80, 30, 'si', 'alta', 12]], dtype=object)

In [29]:
medidas.shape

(4, 5)

###creacion de dataframes por medios de diccionarios

In [39]:
elementos={
    "numero atomico":[1,6,47,88],
    "masa atomica":[1,12,107,226],
    "familia":["no metal","no metal","metal","metal"]
}
elementos

{'numero atomico': [1, 6, 47, 88],
 'masa atomica': [1, 12, 107, 226],
 'familia': ['no metal', 'no metal', 'metal', 'metal']}

In [40]:
tabla_periodica=pd.DataFrame(elementos)
tabla_periodica

   numero atomico  masa atomica   familia
0               1             1  no metal
1               6            12  no metal
2              47           107     metal
3              88           226     metal

In [42]:
tabla_periodica=pd.DataFrame(elementos,index=["H","C","Ag","Ra"],columns=["familia","numero atomico","masa atomica"])
tabla_periodica

     familia  numero atomico  masa atomica
H   no metal               1             1
C   no metal               6            12
Ag     metal              47           107
Ra     metal              88           226

###Creando un dataframe a partir de un array Numpy

In [43]:
datos=np.array([[2,4,6,8],[4,6,7,4],[5,2,3,1]])
datos

array([[2, 4, 6, 8],
       [4, 6, 7, 4],
       [5, 2, 3, 1]])

In [44]:
unidades=pd.DataFrame(datos)
unidades

   0  1  2  3
0  2  4  6  8
1  4  6  7  4
2  5  2  3  1

In [46]:
unidades.index=["la ureña","la predregoza","maria bonita"]
unidades.columns=[2021,2022,2023,2024]
unidades

               2021  2022  2023  2024
la ureña          2     4     6     8
la predregoza     4     6     7     4
maria bonita      5     2     3     1

###Creacion de dataframes con diccionarios

In [52]:
medida_2020={"Ag":2,"Au":8,"Cu":3,"pt":6}
medida_2021={"Ag":4,"Au":1,"Cu":2,"pt":2}
medida_2022={"Ag":5,"Au":2,"Cu":7,"pt":9}

unidades=pd.DataFrame([medida_2020,medida_2021,medida_2022],index=list(range(2020,2023)))
unidades

      Ag  Au  Cu  pt
2020   2   8   3   6
2021   4   1   2   2
2022   5   2   7   9

In [53]:
medida_2020={"Ag":2,"Au":8,"Cu":3,"pt":6}
medida_2021={"Ag":4,"Au":1,"Cu":2,"pt":2}
medida_2022={"Ag":5,"pb":2,"Cu":7,"pt":9}

unidades=pd.DataFrame([medida_2020,medida_2021,medida_2022],index=list(range(2020,2023)))
unidades

      Ag   Au  Cu  pt   pb
2020   2  8.0   3   6  NaN
2021   4  1.0   2   2  NaN
2022   5  NaN   7   9  2.0

# Trabajando con el dataset del titanic

##Inspeccionando los dataframes

In [54]:
titanic=pd.read_csv("/content/titanic-train.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [55]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [57]:
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
461,462,0,3,"Morley, Mr. William",male,34.0,0,0,364506,8.0500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.0,1,1,C.A. 37671,15.9000,NaN,S
540,541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0000,B22,S

In [58]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [59]:
#Devuelve informacion estadistca de los datos
titanic.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [60]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

metodo value_counts

devuelve una estructura conteniendoi los valores presentes en la serie y el numero de ocurrencia de cada valor

In [61]:
titanic.value_counts()

PassengerId  Survived  Pclass  Name                                                  Sex     Age   SibSp  Parch  Ticket    Fare      Cabin  Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female  38.0  1      0      PC 17599  71.2833   C85    C           1
572          1         1       Appleton, Mrs. Edward Dale (Charlotte Lamson)         female  53.0  2      0      11769     51.4792   C101   S           1
578          1         1       Silvey, Mrs. William Baird (Alice Munger)             female  39.0  1      0      13507     55.9000   E44    S           1
582          1         1       Thayer, Mrs. John Borland (Marian Longstreth Morris)  female  39.0  1      1      17421     110.8833  C68    C           1
584          0         1       Ross, Mr. John Hugo                                   male    36.0  0      0      13049     40.1250   A10    C           1
                                                                                                                                                       ..
328          1         2       Ball, Mrs. (Ada E Hall)                               female  36.0  0      0      28551     13.0000   D      S           1
330          1         1       Hippach, Miss. Jean Gertrude                          female  16.0  0      1      111361    57.9792   B18    C           1
332          0         1       Partner, Mr. Austen                                   male    45.5  0      0      113043    28.5000   C124   S           1
333          0         1       Graham, Mr. George Edward                             male    38.0  0      1      PC 17582  153.4625  C91    S           1
890          1         1       Behr, Mr. Karl Howell                                 male    26.0  0      0      111369    30.0000   C148   C           1
Name: count, Length: 183, dtype: int64